basePath: /v1
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API for managing the kernel service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Kernel Service API
  version: "1.0"
paths:
  /restart:
    post:
      description: Restarts the kernel service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Restart the kernel service
      tags:
      - Kernel
  /set-domain:
    post:
      consumes:
      - application/json
      description: Sets the domain for the kernel service
      parameters:
      - description: Domain to set
        in: body
        name: domain
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Set domain for the kernel service
      tags:
      - Configuration
  /set-ip:
    post:
      consumes:
      - application/json
      description: Sets the IP plan for the kernel service
      parameters:
      - description: IP plan to set
        in: body
        name: ip_plan
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Set IP plan for the kernel service
      tags:
      - Configuration
  /start:
    post:
      description: Starts the kernel service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Start the kernel service
      tags:
      - Kernel
  /status:
    get:
      description: Returns the current status of the kernel service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get kernel service status
      tags:
      - Kernel
  /stop:
    post:
      description: Stops the kernel service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Stop the kernel service
      tags:
      - Kernel
swagger: "2.0"
