basePath: /v1
definitions:
  main.Task:
    properties:
      command:
        type: string
      created_at:
        type: string
      error:
        type: string
      id:
        type: string
      output:
        type: string
      status:
        $ref: '#/definitions/main.TaskStatus'
      updated_at:
        type: string
    type: object
  main.TaskStatus:
    enum:
    - pending
    - running
    - finished
    - failed
    type: string
    x-enum-varnames:
    - StatusPending
    - StatusRunning
    - StatusFinished
    - StatusFailed
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API for managing the kernel service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Kernel Service API
  version: "1.0"
paths:
  /status:
    get:
      description: Returns the current status of the kernel service (asynchronous)
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get kernel service status
      tags:
      - Kernel
  /task/{id}:
    get:
      description: Returns the current status of a task
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Task'
      summary: Get task status
      tags:
      - Task
swagger: "2.0"
