name: Go Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.0'  # 使用实际存在的 Go 版本
      
      - name: Install dependencies
        run: go get -v ./...
            
      - name: Run tests
        run: go test -v ./...
      
      - name: Build for multiple platforms
        run: |
          mkdir -p bin
          make all
          
      - name: Create release zip files
        run: |
          cd bin
          zip -r ../kernel-api-linux-amd64.zip kernel-api-linux-amd64
          zip -r ../kernel-api-windows-amd64.zip kernel-api-windows-amd64.exe
          zip -r ../kernel-api-darwin-amd64.zip kernel-api-darwin-amd64
          cd ..
      
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-api-linux-amd64
          path: bin/kernel-api-linux-amd64
      
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-api-windows-amd64
          path: bin/kernel-api-windows-amd64.exe
      
      - name: Upload MacOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-api-darwin-amd64
          path: bin/kernel-api-darwin-amd64
          
      - name: Create/Update Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}  # 使用运行编号作为版本号
          name: Release v${{ github.run_number }}
          files: |
            ./kernel-api-linux-amd64.zip
            ./kernel-api-windows-amd64.zip
            ./kernel-api-darwin-amd64.zip
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}