name: Go Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的Ubuntu运行器

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'  # 更新为实际存在的Go版本

      - name: Install dependencies
        run: go get -v ./...
        
      - name: Run tests
        run: go test -v ./...

      - name: Build for Linux x64
        run: |
          GOOS=linux GOARCH=amd64 go build -o kernel-api
          zip -r kernel-api.zip kernel-api

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-api-linux-x64  # 构建产物名称
          path: kernel-api 
      
      - name: Create/Update Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: |
            ./kernel-api.zip
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}